# -*- coding: utf-8 -*-
"""irisdeploying.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qV05yAi0iMNDCrya7TOu3lBiKpLKczxB
"""

#!pip install streamlit
import streamlit as st
import pickle



def get_Id():
    Id = st.text_input("Id of Iris")
    return Id

def get_SepalLength():
    SepalLength = st.text_input("SepalLength of Iris")
    return SepalLength

def get_SepalWidth():
    SepalWidth = st.text_input("SepalWidth of Iris")
    return SepalWidth

def get_PetalLength():
    PetalLength = st.text_input("PetalLength")
    return PetalLength

def get_PetalWidth():
    PetalWidth = st.text_input("PetalWidth of Iris")
    return PetalWidth

def predict_species(id,sl,sw,pl,pw):
    loaded_model = pickle.load(open('decision_tree_model(1).pkl','rb'))
    new_data = [[float(id),float(sl),float(sw),float(pl),float(pw),]]
    prediction = loaded_model.predict(new_data)
    st.write("Prediction with new data: ")
    st.write(prediction)




if __name__ == "__main__":
    st.title('Iris Species prediction with Decision Tree model')
    st.image('iris.jpg')
    Id = get_Id()
    Sepal_Length = get_SepalLength()
    Sepal_Width = get_SepalWidth()
    Petal_Length = get_PetalLength()
    Petal_Width=get_PetalWidth()
    st.write("The parameters you entered are: ")
    st.write("Id", Id)
    st.write("Sepal length ", Sepal_Length)
    st.write("Sepal Width ", Sepal_Width)
    st.write("Petal length ", Petal_Length)
    st.write("Petal Width ", Petal_Width)


if st.button("Predict"):
    predict_species(Id,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width)

